name: stl_analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - numpy
  - os
  - pathlib
  - censusdata
  - altair
  - statsmodels
  - streamlit
  - folium
  - streamlit_folium